# ==============================================================================
# Base config for training pipeline
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. DATA LOADING
# ------------------------------------------------------------------------------
data:
  directory: C:\Users\proxi\Documents\coding\TOF_data
  loader_config_key: h5
  parse_data_directories: true
  # Feature and output columns defined here for organization
  feature_columns: ['tof_values', 'mid1', 'mid2', 'retardation', 'elevation', 'x', 'y']
  output_columns: ['kinetic_energy']
  pass_energy: true
  live_plot: false

# ------------------------------------------------------------------------------
# 2. DATA PREPROCESSING PIPELINE (in execution order)
# ------------------------------------------------------------------------------
preprocessing:
  # Step 1: Masking
  masking:
    enabled: true
    x_range: [406, 408]
    y_range: [-16, 16]

  # Step 2: Pass energy transformation
  pass_energy:
    enabled: true

  # Step 3: Log transform
  log_transform:
    enabled: true
    columns: ['tof_values']
    base: 2.0

  # Step 4: Scaling
  scaling:
    enabled: true
    type: MinMaxScaler
    feature_columns: ['tof_values', 'mid1', 'mid2', 'retardation', 'elevation', 'x', 'y']

  # Step 5: Feature engineering
  feature_engineering:
    interactions:
      enabled: true
      columns: ['tof_values', 'mid1', 'mid2', 'retardation']
    squared:
      enabled: false
    sine:
      enabled: false

# ------------------------------------------------------------------------------
# 3. TRAINING PARAMETERS
# ------------------------------------------------------------------------------
training:
  val_size: 0.2
  test_size: 0.2
  random_state: 42

# ------------------------------------------------------------------------------
# 4. MODEL CONFIGURATION
# ------------------------------------------------------------------------------
model:
  type: "MLPRegressor"
  params:
    hidden_layers: [16, 32, 16]
    activations: ['leaky_relu', 'leaky_relu', 'swish']
    learning_rate: 0.1
    epochs: 20
    batch_size: 64
    early_stopping_patience: 10
    reduce_lr_factor: 0.2
    reduce_lr_patience: 20
    reduce_lr_min_lr: 1e-6
    monitor_metric: "val_loss"

# ------------------------------------------------------------------------------
# 5. MODEL OUTPUT DIRECTORY
# ------------------------------------------------------------------------------
model_output_dir: /sdf/scratch/users/a/ajshack/hp_database