# ==============================================================================
# Base config for training pipeline
# This file can be updated by the user.
# ==============================================================================

# ------------------------------------------------------------------------------
# 1. GENERAL
# ------------------------------------------------------------------------------
general:
  n_samples_plot: 10000
  log_log_plot: true

# ------------------------------------------------------------------------
# 2. GENERATE REPORT CONFIGURATION
# ------------------------------------------------------------------------

confirmation_plots:
  # For each "stage", a list of plots to generate
  data_loader:
    scatter:
      id1:
        title: Data loaded
        axes: [ "retardation", "tof" ]
        color_by: initial_ke
      id2:
        title: Data loaded
        axes: [ "mid1", "tof" ]
        color_by: initial_ke

  splitter:
    histogram:
      id1:
        title: Total data split
        live_plot: true
        report: true
        keys: total
      id2:
        title: Kinetic energy data split
        live_plot: true
        report: true
        keys: initial_ke
        color_by: [ "train", "validation", "test" ]
      id3:
        title: Retardation data split
        live_plot: true
        report: true
        keys: retardation
        color_by: [ "train", "validation", "test" ]
      id4:
        title: Voltage data split
        live_plot: true
        report: true
        keys: ["mid1", "mid2"]
        color_by: [ "train", "validation", "test" ]


  preprocessor: # this name implies that all plots should have before scaling and after scaling
    scatter:
      id1:
        title: Process data
        axes: [ "tof", "initial_ke" ]
        color_by: retardation

  trainer:
    scatter:
      id1:
        title: true vs predicted
        axes: [ "true_energy", "predicted_energy" ]
        color_by: retardation
      id2:
        title: residuals vs predicted
        axes: [ "residuals", "predicted_energy" ]
        color_by: retardation
      id3:
        title: training learning curve
        axes: [ "epochs", "loss" ]
    histogram:
      id1:
        title: Retardation data split
        live_plot: true
        report: true
        keys: residuals

# ------------------------------------------------------------------------------
# 4. SCALING SAVE/LOAD
# ------------------------------------------------------------------------------
scaler:
  load: true
  save: true

