# config/class_mapping_config.yaml

# Data Loaders
Loader:
  CSVLoader: "src.tof_ml.data.loaders.csv_loader.CSVLoader"
  H5Loader: "src.tof_ml.data.loaders.h5_loader.H5Loader"
  EnhancedH5Loader: "src.tof_ml.data.loaders.enhanced_h5_loader.EnhancedH5Loader"
  SimulationLoader: "src.tof_ml.data.loaders.simulation_loader.SimulationLoader"

# Data Transformers
Transformer:
  Normalizer: "src.tof_ml.data.transformers.normalizer.Normalizer"
  LogTransformer: "src.tof_ml.data.transformers.log_transformer.LogTransformer"
  FeatureEngineer: "src.tof_ml.data.transformers.feature_engineer.FeatureEngineer"
  Outlier: "src.tof_ml.data.transformers.outlier_detector.OutlierDetector"

# Data Splitters
Splitter:
  RandomSplitter: "src.tof_ml.data.splitters.random_splitter.RandomSplitter"
  StratifiedSplitter: "src.tof_ml.data.splitters.stratified_splitter.StratifiedSplitter"
  TimeSplitter: "src.tof_ml.data.splitters.time_splitter.TimeSplitter"

# Models
Model:
  MLPKerasRegressor: "src.tof_ml.models.tof_to_energy_model.MLPKerasRegressor"
  LinearModel: "src.tof_ml.models.linear_model.LinearModel"
  RandomForestModel: "src.tof_ml.models.random_forest_model.RandomForestModel"
  XGBoostModel: "src.tof_ml.models.xgboost_model.XGBoostModel"

# Callbacks
Callback:
  EarlyStopping: "tensorflow.keras.callbacks.EarlyStopping"
  ModelCheckpoint: "tensorflow.keras.callbacks.ModelCheckpoint"
  ReduceLROnPlateau: "tensorflow.keras.callbacks.ReduceLROnPlateau"
  TensorBoard: "tensorflow.keras.callbacks.TensorBoard"
