# config/class_mapping_config.yaml

# Data Loaders
Loader:
  MNISTLoader: "plugins.loaders.mnist_loader.MNISTLoader"
  MNISTConvLoader: "plugins.loaders.mnist_loader.MNISTConvLoader"

# Data Transformers
Transformer:
  Normalizer: "src.tof_ml.data.transformers.normalizer.Normalizer"
  StandardScaler: "src.tof_ml.data.transformers.scaler.StandardScaler"

# Data Splitters
Splitter:
  RandomSplitter: "src.tof_ml.data.splitters.RandomSplitter"

# Models
Model:
  MNISTKerasModel: "plugins.models.mnist_keras_model.MNISTKerasModel"
  MNISTConvModel: "plugins.models.mnist_keras_model.MNISTConvModel"

# Report Generators
ReportGenerator:
  MNISTReportGenerator: "plugins.report_generators.MNIST_report.MNISTReportGenerator"
  MNISTConvReportGenerator: "plugins.report_generators.MNIST_report.MNISTConvReportGenerator"

# Database Adapters
Database:
  SQLiteDB: "plugins.database.sqlite_db.SQLiteDB"
  PostgresDB: "plugins.database.postgres_db.PostgresDB"