# config/class_mapping_config.yaml

# Data Loaders
Loader:
  EnhancedH5Loader: "plugins.loaders.enhanced_h5_loader.EnhancedH5Loader"
  MNISTLoader: "plugins.loaders.mnist_loader.MNISTLoader"
  MNISTConvLoader: "plugins.loaders.mnist_loader.MNISTConvLoader"

# Data Transformers
Transformer:
  Normalizer: "src.tof_ml.data.transformers.normalizer.Normalizer"
  StandardScaler: "src.tof_ml.data.transformers.scaler.StandardScaler"

# Data Splitters
Splitter:
  RandomSplitter: "src.tof_ml.data.splitters.RandomSplitter"
  TimeSeriesSplitter: "src.tof_ml.data.splitters.time_series_splitter.TimeSeriesSplitter"

# Models
Model:
  MLPKerasClassifier: "src.tof_ml.models.keras_classifier.MLPKerasClassifier"
  MNISTKerasModel: "plugins.models.mnist_keras_model.MNISTKerasModel"
  MNISTConvModel: "plugins.models.mnist_keras_model.MNISTConvModel"

# Report Generators
ReportGenerator:
  ClassificationReportGenerator: "src.tof_ml.reporting.report_generator.ClassificationReportGenerator"
  RegressionReportGenerator: "src.tof_ml.reporting.report_generator.RegressionReportGenerator"
  MNISTReportGenerator: "plugins.report_generators.MNIST_report.MNISTReportGenerator"

# Database Adapters
Database:
  SQLiteDB: "plugins.database.sqlite_db.SQLiteDB"
  PostgresDB: "plugins.database.postgres_db.PostgresDB"