
# Database configuration for ML Provenance Framework

# Database type (currently only sqlite is supported)
type: "sqlite"

# Database path
path: "./data/ml_provenance.db"

# Connection settings
connection:
  timeout: 30
  
# Performance settings
performance:
  enable_wal_mode: true
  cache_size: 10000
  
# Backup settings (optional)
backup:
  enabled: false
  interval_hours: 24
  backup_dir: "./data/backups"
  
# Cleanup settings (optional)
cleanup:
  enabled: false
  retain_days: 30
  
# Additional settings
settings:
  foreign_keys: true
  journal_mode: "WAL"