# plot_config.yaml
# ==============================================================================
# Base config for plotting pipeline
# This file can be updated by the user or overridden via command-line arguments.
# ==============================================================================

# --------------------------------------------------------------------------
# 1. DATA LOADING CONFIGURATION
# --------------------------------------------------------------------------
data:
  directory: /Users/proxi/Documents/coding/TOF_data          # Path to the directory containing data files
  loader_config_key: old_discrete  # Key identifying the data loader to use
  parameters:
    mid1_ratio: null                       # Range for mid1_ratio (e.g., [0.1, 0.5])
    mid2_ratio: null                       # Range for mid2_ratio (e.g., [0.2, 0.8])
    retardation: null                      # Range for retardation (e.g., [0.5, 1.5])
    number_of_samples: 5000                # Number of samples to plot

# --------------------------------------------------------------------------
# 2. PLOTTING CONFIGURATION
# --------------------------------------------------------------------------
plotting:
  pass_energy: false                       # Whether to plot pass energy instead of initial_ke
  filepath: /Users/proxi/Documents/coding/TOF_data   # Path to save the plots (if null, show plots)

# --------------------------------------------------------------------------
# 3. NOTION DATABASE CONFIGURATION
# --------------------------------------------------------------------------
notion:
  enabled: true                           # Whether to push results to Notion

# --------------------------------------------------------------------------
# 4. GOOGLE DRIVE CONFIGURATION
# --------------------------------------------------------------------------
google_drive:
  upload_drive: true                      # Whether to upload plots to Google Drive

