# config/database_config.yaml

# Database type (only sqlite supported for now)
type: "sqlite"

# Path to database file (use :memory: for in-memory database)
path: "./output/experiments.db"

# Connection options
options:
  timeout: 30
  isolation_level: "DEFERRED"

# Logging options
logging:
  enabled: true
  level: "INFO"
