notion:
  token_file: notion_token.json
  database_id: 160d57b3c56d808986eed4a41b7e5512

google_drive:
  folder_id: 1s6n7YgoUoo8DHeYJqyaSR-l_TQlNeTLd
  scopes:
    - https://www.googleapis.com/auth/drive.file
  token_file: token.json
  client_secret_file: /Users/proxi/Documents/coding/goauth/client_secret_1058501869990-5nnvgvmsqnt61vkns6vd21v15798f8pn.apps.googleusercontent.com.json
