csv_loader_1:
  type: CSVDataLoader
  params:
    folder_path: "/sdf/scratch/users/a/ajshack/tmox1016823/model_trials/2"

csv_loader_2:
  type: CSVDataLoader
  params:
    folder_path: "/sdf/scratch/users/a/ajshack/tmox1016823/model_trials/2"

data_source:
  type: csv
  path: data/raw/training_data.csv
filters:
  - column: date
    start: 2021-01-01
    end: 2021-12-31
