
# loader_config.yaml
# ==============================================================================
# Contains configurations for each possible data loader in the project
# ==============================================================================

vandana_continuous_nm:
  loader_class: src.tof_ml.data.nm_csv_data_loader.NMCsvDataLoader
  loader_type: csv

old_discrete:
  loader_class: src.tof_ml.data.h5_data_loader.H5DataLoader
  loader_type: h5

OtherData:
  loader_class: src.data.other_data_loader.OtherDataLoader
  loader_type: otherloadertype
