# config/mnist_cnn_config.yaml

# Experiment configuration
experiment_name: "mnist_cnn_classification"
output_dir: "./output"
use_database: true

# Data configuration
data:
  dataset_name: "MNIST"
  dataset_path: "mnist"  # Dummy path for validation
  force_reload: false  # Set to true to force reloading data

# Plugin configuration
plugins:
  data_loader: "MNISTConvLoader"
  model: "MNISTConvModel"
  report_generator: "MNISTConvReportGenerator"

# Transformations configuration (updated with explicit parameters)
transformations:
  normalize: true
  one_hot: false

# Data splitting configuration (updated with explicit parameters)
data_splitting:
  type: "RandomSplitter"
  train_ratio: 0.7
  val_ratio: 0.15
  test_ratio: 0.15
  random_seed: 42

# Model-specific configuration
model:
  type: "MNISTConvModel"

  # CNN Architecture hyperparameters
  conv_filters: [32, 64]
  kernel_sizes: [3, 3]
  pool_sizes: [2, 2]

  # Dense layer hyperparameters
  dense_layers: [128]
  dropout_rate: 0.3

  # Activation functions
  activations: ["relu", "relu", "relu"]
  output_activation: "softmax"
  output_units: 10

  # Training hyperparameters
  learning_rate: 0.001
  optimizer_name: "Adam"
  loss: "sparse_categorical_crossentropy"
  metrics: ["accuracy"]

  # Training configuration
  epochs: 20
  batch_size: 64

  # Early stopping
  early_stopping:
    enabled: true
    monitor: "val_loss"
    patience: 5
    restore_best_weights: true

  # Model checkpointing
  checkpoint:
    enabled: true
    monitor: "val_loss"
    save_best_only: true

  # Model lineage tracking configuration (NEW)
  lineage_tracking:
    enabled: true
    frequency: "epoch"  # Options: "epoch", "checkpoint", "milestone", "batch"
    track_parameters: true  # Track hyperparameter changes
    track_gradients: false  # Track gradient statistics (future feature)

# Report configuration
reporting:
  enabled_reports: ["data", "training", "evaluation", "summary"]
  style: "tableau-colorblind10"

# Provenance configuration
provenance:
  enabled: true
  track_data_lineage: true
  track_model_lineage: true
  save_intermediate: false  # Save intermediate transformation results

# Metrics configuration
metrics:
  custom_metrics_enabled: true
  predefined_categories:
    data: ["*_samples", "data_shape_*", "*_time_seconds", "completeness_ratio"]
    training: ["*_loss", "*_accuracy", "training_time_seconds", "epochs_completed", "learning_rate"]
    evaluation: ["test_*", "evaluation_time_seconds", "confusion_matrix"]

# Artifact configuration
artifacts:
  save_predictions: true
  save_checkpoints: true
  save_logs: true
  compression: "gzip"