# config/tof_data_config.yaml

# Experiment metadata
experiment_name: "tof_data_processing"
output_dir: "./output"
provenance:
  enabled: true
  db_path: "./provenance"

# Class mapping configuration
class_mapping_path: "config/class_mapping_config.yaml"

# Data configuration
data:
  loader_config_key: "EnhancedH5Loader"
  dataset_path: "C:/Users/proxi/Documents/coding/TOF_data"
  n_samples: null  # Use all samples
  batch_size: 10000  # Load data in batches of 10000 samples
  feature_columns: ["initial_ke", "retardation", "elevation", "mid1", "mid2"]
  target_columns: ["tof", "y"]
  feature_names: ["Initial Kinetic Energy", "Retardation Voltage", "Elevation", "Blade 22 Voltage Ratio", "Blade 25 Voltage Ratio"]
  target_names: ["Time of Flight", "Final Y Position"]
  # Voltage configurations
  mid1: [0.2, 0.2]
  mid2: [0.2, 0.2]

# Preprocessing configuration
preprocessing:
  transformers:
    - type: "Normalizer"
      columns: ["tof", "x", "y"]
      method: "standard"
      clip: true
      clip_range: [-3, 3]
    - type: "LogTransformer"
      columns: ["tof"]
      base: 10
      offset: 1e-6
      handle_negatives: "offset"

# Data splitting configuration
data_splitting:
  type: "RandomSplitter"
  test_size: 0.2
  val_size: 0.2
  random_state: 42

# Model configuration
model:
  type: "MLPKerasRegressor"
  hidden_layers: [64, 128, 64]
  activations: ["relu", "relu", "relu"]
  learning_rate: 0.001
  optimizer_name: "Adam"
  epochs: 100
  batch_size: 32
  regularization: 0.01
  dropout: 0.2
  early_stopping:
    enabled: true
    patience: 10
    monitor: "val_loss"
  checkpoint:
    enabled: true
    save_best_only: true
    monitor: "val_loss"

# Reporting configuration
reporting:
  enabled_reports: ["data", "training", "evaluation", "summary"]
  plots:
    dpi: 300
    style: "seaborn-darkgrid"

# Database configuration
use_database: true
database:
  config_path: "config/database_config.yaml"
