# config/tof_model_config.yaml

# Experiment metadata
experiment_name: "tof_energy_model"
output_dir: "./output"
provenance:
  enabled: true
  db_path: "./provenance"

# Class mapping configuration
class_mapping_path: "config/class_mapping_config.yaml"

# Data configuration
data:
  dataset_path: "./output/tof_data_preprocessing_20250331_120000/data"  # Path to preprocessed data
  feature_columns: ["tof", "retardation", "amplitude"]
  target_columns: ["energy"]
  feature_names: ["Time of Flight", "Retardation Voltage", "Signal Amplitude"]
  target_names: ["Energy (eV)"]

# Model configuration
model:
  type: "MLPKerasRegressor"
  hidden_layers: [64, 128, 64]
  activations: ["relu", "relu", "relu"]
  learning_rate: 0.001
  optimizer_name: "Adam"
  epochs: 100
  batch_size: 32
  regularization: 0.01
  dropout: 0.2
  early_stopping:
    enabled: true
    patience: 10
    monitor: "val_loss"
  checkpoint:
    enabled: true
    save_best_only: true
    monitor: "val_loss"

# Reporting configuration
reporting:
  enabled_reports: ["data", "training", "evaluation", "summary"]
  plots:
    dpi: 300
    style: "seaborn-darkgrid"

# Database configuration
use_database: true
database:
  config_path: "config/database_config.yaml"
